### ISSUE TITLE
10-3 Extract<T,K> 설명 오류

### ISSUE THREAD

**Issue by egg528** [winterlood/onebite-typescript-notbook#2]
안녕하세요 @winterlood 님
우선 좋은 자료 정말 감사합니다 👍 
덕분에 TypeScript를 수월하게 학습할 수 있었습니다.
 

<img width="831" alt="스크린샷 2023-06-11 오전 12 15 36" src="https://github.com/winterlood/onebite-typescript-notbook/assets/62459196/490a4b91-1c3b-4a65-a52e-14fd48c88368">
자료로 공부하던 중 설명과 코드 결과가 잘못된 부분이 있어 이슈 남겨둡니다.

좋은 자료 다시 한번 감사합니다 : )

**Comment by winterlood** [comment]
안녕하세요 @egg528 님!
앗 제가 실수를 했네요 확인 감사합니다! 수정해두었습니다

https://ts.winterlood.com/1c7e7130-67d6-4028-ad06-448c65863dab#f7325a973d5f4c958fb89cff246b42b3

![image](https://github.com/winterlood/onebite-typescript-notbook/assets/46296754/2238ec3b-b725-4790-9c99-80c1d641262a)
